# Generated by Django 4.2.29 on 2026-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_face_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipendevent',
            name='date',
            field=models.DateField(help_text='Main payout date or start of payout period.'),
        ),
    ]
