# Generated by Django 4.2.29 on 2026-03-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiary_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0008_verificationattempt_template_debug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimant_type', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('representative', 'Authorized Representative')], default='beneficiary', max_length=20)),
                ('reason', models.TextField(help_text='Why manual verification is being requested.')),
                ('notes', models.TextField(blank=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('liveness_passed', models.BooleanField(null=True)),
                ('liveness_score', models.FloatField(blank=True, null=True)),
                ('id_type_checked', models.CharField(blank=True, max_length=50)),
                ('id_verified', models.BooleanField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_verification_requests', to='beneficiaries.beneficiary')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_manual_verification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manual_verification_requests', to=settings.AUTH_USER_MODEL)),
                ('stipend_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_verification_requests', to='verification.stipendevent')),
                ('verification_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_requests', to='verification.verificationattempt')),
            ],
            options={
                'db_table': 'fans_manual_verification_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceUpdateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('repeated_failure', 'Repeated Verification Failure'), ('appearance_change', 'Major Appearance Change'), ('poor_original', 'Poor Original Registration'), ('staff_decision', 'Staff Decision / Other')], max_length=30)),
                ('action', models.CharField(choices=[('replace', 'Replace Primary Embedding'), ('augment', 'Add as Additional Template')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('new_embedding_data', models.BinaryField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_update_requests', to='beneficiaries.beneficiary')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_face_update_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_face_update_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fans_face_update_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
