# Generated by Django 4.2.29 on 2026-03-22 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_beneficiary_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0009_approval_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimant_type', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('representative', 'Authorized Representative')], default='beneficiary', max_length=20)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='claimed', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_special_additional', models.BooleanField(default=False, help_text='True if this is a second claim approved via SpecialClaimRequest.')),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_claims', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_records', to='beneficiaries.beneficiary')),
                ('claimed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to=settings.AUTH_USER_MODEL)),
                ('stipend_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_records', to='verification.stipendevent')),
                ('verification_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_records', to='verification.verificationattempt')),
            ],
            options={
                'db_table': 'fans_claim_records',
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialClaimRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why a second claim is being requested.')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_claim_requests', to='beneficiaries.beneficiary')),
                ('original_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_requests', to='verification.claimrecord')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_special_claim_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_special_claim_requests', to=settings.AUTH_USER_MODEL)),
                ('stipend_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_claim_requests', to='verification.stipendevent')),
            ],
            options={
                'db_table': 'fans_special_claim_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
