# Generated by Django 4.2.29 on 2026-03-22 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0005_add_representative_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0010_claimrecord_specialclaimrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationattempt',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='beneficiaries.representative'),
        ),
        migrations.CreateModel(
            name='RepresentativeFaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('representative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to='beneficiaries.representative')),
            ],
            options={
                'db_table': 'fans_rep_face_embeddings',
            },
        ),
    ]
