# Generated by Django 4.2.29 on 2026-03-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0005_add_representative_model'),
        ('verification', '0011_add_rep_face_embedding_and_attempt_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrecord',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_records', to='beneficiaries.representative'),
        ),
    ]
