# Generated by Django 4.2.29 on 2026-03-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0012_add_representative_to_claim_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationattempt',
            name='demo_mode_active',
            field=models.BooleanField(default=False, help_text='True if Assisted Rollout Mode (DEMO_MODE) was active at the time of this verification (assisted-rollout threshold applied).'),
        ),
    ]
