# Generated by Django 4.2.21 on 2026-05-10 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0013_alter_verificationattempt_demo_mode_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PHP amount paid out for this claim (snapshot from StipendEvent.amount).', max_digits=12),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_record_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='payout_remarks',
            field=models.TextField(blank=True, help_text='Free-text remarks captured at release (kept distinct from the verification notes field).'),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated reference / transaction number, e.g. RC-2026-05-00012.', max_length=64),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='Moment the payout was released to the beneficiary.', null=True),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='released_by',
            field=models.ForeignKey(blank=True, help_text='Staff/admin who released the cash (defaults to claimed_by).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='claimrecord',
            name='verification_method',
            field=models.CharField(choices=[('face_recognition', 'Face Recognition'), ('manual_review', 'Manual Verification (Approved)'), ('fallback_id', 'Fallback ID Check'), ('admin_override', 'Admin Override')], default='face_recognition', help_text='How identity was confirmed for this payout.', max_length=30),
        ),
        migrations.AddField(
            model_name='stipendevent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard payout amount per beneficiary for this event (PHP).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='claimrecord',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed / Released'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='claimed', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='claimrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_special_additional', False), ('status', 'claimed')), fields=('beneficiary', 'stipend_event'), name='unique_claimed_per_beneficiary_event'),
        ),
    ]
