# Generated by Django 4.2.21 on 2026-05-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0016_stipendevent_custom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipendevent',
            name='payout_end_time',
            field=models.TimeField(blank=True, help_text='Daily end time for claiming (Asia/Manila). Leave blank = all day.', null=True),
        ),
        migrations.AddField(
            model_name='stipendevent',
            name='payout_start_time',
            field=models.TimeField(blank=True, help_text='Daily start time for claiming (Asia/Manila). Leave blank = all day.', null=True),
        ),
    ]
