# Generated by Django 4.2.21 on 2026-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0019_stipend_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationattempt',
            name='decision',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('not_verified', 'Not Verified'), ('manual_review', 'Manual Review'), ('denied', 'Denied')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verificationattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='verificationattempt',
            index=models.Index(fields=['beneficiary', 'decision', 'timestamp'], name='fans_verifi_benefic_2821d6_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationattempt',
            index=models.Index(fields=['performed_by', 'timestamp'], name='fans_verifi_perform_022b1e_idx'),
        ),
    ]
