# Generated by Django 4.2.21 on 2026-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0020_add_dashboard_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipendevent',
            name='late_approval_reason',
            field=models.TextField(blank=True, help_text='Required when approval happens after the payout date has already passed.'),
        ),
    ]
