# Generated by Django 4.2.21 on 2026-08-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0021_add_late_approval_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrecord',
            name='verification_method',
            field=models.CharField(choices=[('face_recognition', 'Face Recognition'), ('manual_review', 'Manual Verification (Approved)'), ('fallback_id', 'Manual Verification (ID Check)'), ('admin_override', 'Admin Override')], default='face_recognition', help_text='How identity was confirmed for this payout.', max_length=30),
        ),
    ]
