# Generated by Django 4.2.21 on 2026-08-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0013_shared_representative_review'),
        ('verification', '0022_update_display_labels_v2_2_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceupdaterequest',
            name='duplicate_match_beneficiary',
            field=models.ForeignKey(blank=True, help_text='A different beneficiary whose face matched this new capture.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_update_duplicate_flags', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='faceupdaterequest',
            name='duplicate_match_score',
            field=models.FloatField(blank=True, help_text='Face similarity score against duplicate_match_beneficiary (0-1).', null=True),
        ),
    ]
