# Generated by Django 4.2.21 on 2026-09-02 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0023_faceupdaterequest_duplicate_match_beneficiary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable dataset/study title.', max_length=200)),
                ('protocol_version', models.CharField(help_text='Identifier for the controlled-evaluation protocol/version this dataset follows.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('collecting', 'Collecting'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When trial collection actually began.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the dataset was finalized.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Researcher/operator who defined this dataset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fans_evaluation_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationTrial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique trial identifier.', primary_key=True, serialize=False)),
                ('trial_status', models.CharField(choices=[('pending', 'Pending (attempt not yet run/recorded)'), ('completed', 'Completed (system output recorded)')], db_index=True, default='pending', max_length=20)),
                ('participant_code', models.CharField(help_text='Pseudonymous code identifying the presenter for this trial. Not a name/ID.', max_length=100)),
                ('target_identity_code', models.CharField(help_text='Pseudonymous code for the enrolled identity being claimed/compared against.', max_length=100)),
                ('identity_ground_truth', models.CharField(choices=[('genuine', 'Genuine (enrolled presenter)'), ('impostor', 'Impostor (different presenter)')], db_index=True, max_length=20)),
                ('presentation_ground_truth', models.CharField(choices=[('bona_fide', 'Bona Fide / Live Presenter'), ('print_photo', 'Print / Photo Attack'), ('screen_replay', 'Screen Replay Attack'), ('other_attack', 'Other Presentation Attack'), ('not_tested', 'Not Tested / Not Applicable to This Trial')], default='not_tested', max_length=20)),
                ('system_decision', models.CharField(blank=True, choices=[('verified', 'Verified'), ('not_verified', 'Not Verified'), ('manual_review', 'Manual Review'), ('denied', 'Denied')], db_index=True, help_text='FANS-C decision actually recorded for this trial. Null until the trial is run.', max_length=20, null=True)),
                ('similarity_score', models.FloatField(blank=True, help_text='FaceNet cosine similarity for this trial. Null (not 0.0) when comparison never occurred, e.g. blocked by a liveness gate.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('review_threshold_snapshot', models.FloatField(blank=True, help_text='SystemConfig.get_threshold() value at trial time (manual-review floor).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('auto_verify_threshold_snapshot', models.FloatField(blank=True, help_text='SystemConfig.get_auto_verify_threshold() value at trial time (auto-verify ceiling).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('liveness_passed', models.BooleanField(blank=True, null=True)),
                ('liveness_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('anti_spoof_passed', models.BooleanField(blank=True, null=True)),
                ('anti_spoof_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('pa_score', models.FloatField(blank=True, help_text='Presentation-attack heuristic score (0=clean, 1=suspicious), mirrors LivenessTransaction.pa_score.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('verification_duration_ms', models.PositiveIntegerField(blank=True, help_text='Placeholder for end-to-end verification timing in milliseconds. Not populated by BPA-1 — no timing instrumentation exists yet. Intended to be filled by BPA-2 once real capture-to-decision timing is measured. Must never be fabricated; leave null until a real measurement exists.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('human_review_outcome', models.CharField(blank=True, choices=[('confirmed_genuine', 'Confirmed Genuine'), ('confirmed_impostor', 'Confirmed Impostor'), ('inconclusive', 'Inconclusive')], max_length=20)),
                ('human_review_notes', models.TextField(blank=True)),
                ('human_review_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_at', models.DateTimeField(blank=True, help_text='When the system output for this trial was actually recorded (distinct from created_at).', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Researcher/operator who administered this trial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_trials', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='verification.evaluationdataset')),
                ('human_review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_reviewed_evaluation_trials', to=settings.AUTH_USER_MODEL)),
                ('verification_attempt', models.ForeignKey(blank=True, help_text='Optional link to the real VerificationAttempt this trial reused, if the controlled workflow ran a live attempt rather than a fully separate test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_trials', to='verification.verificationattempt')),
            ],
            options={
                'db_table': 'fans_evaluation_trials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'identity_ground_truth'], name='fans_evalua_dataset_d28dc6_idx'), models.Index(fields=['dataset', 'system_decision'], name='fans_evalua_dataset_80ae57_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationtrial',
            constraint=models.CheckConstraint(check=models.Q(('verification_duration_ms__isnull', True), ('verification_duration_ms__gte', 0), _connector='OR'), name='evaluationtrial_duration_non_negative'),
        ),
    ]
