# Generated by Django 4.2.21 on 2026-09-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0025_evaluationtrial_evaluation_session_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtrial',
            name='challenge_direction',
            field=models.CharField(blank=True, help_text='Challenge direction shown to the researcher for this trial (liveness.get_random_challenge()), if an active challenge was attempted.', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='head_movement_completed',
            field=models.BooleanField(default=False, help_text='Researcher-attested: whether the head-movement challenge was actually performed. Mirrors VerificationAttempt.head_movement_completed.'),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='liveness_captured_at',
            field=models.DateTimeField(blank=True, help_text='When stage-1 liveness processing completed successfully (proof embedding stored).', null=True),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='liveness_pathway',
            field=models.CharField(blank=True, choices=[('passive_only', 'Passive Only (anti-spoof + PAD, no active challenge attested)'), ('active_challenge', 'Active Challenge (head-movement challenge attested and combined into the liveness score)'), ('failed_passive', 'Failed — passive anti-spoof/PAD gate rejected before any challenge was considered'), ('failed_active', 'Failed — active challenge was attempted but liveness validation still failed')], help_text='Which production liveness pathway this trial actually exercised. Production is risk-based (the interactive challenge is not shown on every real attempt); BPA-2.1 makes the researcher choose per trial and records which pathway ran, rather than silently forcing one policy — see BIOMETRIC-EVALUATION-METHODOLOGY.md.', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='liveness_proof_embedding',
            field=models.BinaryField(blank=True, help_text='Encrypted FaceNet embedding from the neutral/liveness-proof frame (stage 1). Used for both identity matching and the same-face check against the final frame.', null=True),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='lookalike_escalation_applied',
            field=models.BooleanField(default=False, help_text='Whether lookalike/duplicate-face escalation changed the decision for this trial.'),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='matcher_base_decision',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('not_verified', 'Not Verified'), ('manual_review', 'Manual Review'), ('denied', 'Denied')], help_text='Raw decide_base_outcome() result before any post-score override. Null when no comparison was reached (pre-comparison denial).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='quality_override_applied',
            field=models.BooleanField(default=False, help_text='Whether the low-quality-forces-manual-review override changed the decision for this trial.'),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='representative_fallback_blocked',
            field=models.BooleanField(default=False, help_text='True if a representative-target trial was denied because the live face matched the BENEFICIARY instead of the representative (never a valid match).'),
        ),
    ]
