# Generated by Django 4.2.21 on 2026-09-02 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0026_evaluationtrial_challenge_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationtrial',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='Raw FaceNet cosine similarity for this trial (legal domain [-1, 1] — see face_utils.cosine_similarity, never clamped). Null (not 0.0) when comparison never occurred, e.g. blocked by a liveness gate. Not to be confused with the positive-valued operating threshold configuration (BPA-3.2 §3).', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
