# Generated by Django 4.2.21 on 2026-09-02 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0027_evaluationtrial_similarity_score_cosine_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationdataset',
            name='purpose',
            field=models.CharField(choices=[('research_study', 'Research Study (Final Evaluation)'), ('pilot_calibration', 'Pilot / Calibration'), ('qa_synthetic', 'QA / Synthetic / Developer Test')], db_index=True, default='qa_synthetic', help_text='Classifies this dataset so QA/synthetic/pilot data can never be mistaken for a real, final controlled study result. Defaults to QA_SYNTHETIC (the conservative choice for any dataset not explicitly marked otherwise) — a dataset is only ever treated as a final study result when it is BOTH purpose=RESEARCH_STUDY AND status=COMPLETED (see is_final_study_result).', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='withdrawal_reason',
            field=models.TextField(blank=True, help_text='Reason recorded for withdrawal (e.g. "participant withdrew consent"). Required whenever withdrawn=True.'),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='withdrawn',
            field=models.BooleanField(db_index=True, default=False, help_text='True once this trial has been withdrawn/excluded by participant request. Excluded from all biometric metric calculations; the row itself is never deleted.'),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationtrial',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, help_text='Staff member (President-tier — see views._evaluation_admin_required/is_president) who recorded the withdrawal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_evaluation_trials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evaluationtrial',
            index=models.Index(fields=['dataset', 'withdrawn'], name='fans_evalua_dataset_a327d5_idx'),
        ),
    ]
