# Generated by Django 4.2.21 on 2026-09-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0028_evaluationdataset_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationdataset',
            name='amended_after_finalization_at',
            field=models.DateTimeField(blank=True, help_text='Set to the time of the most recent participant withdrawal recorded AFTER this dataset was originally finalized (completed_at). Null means the finalized result has never been amended. Never cleared once set — see has_post_finalization_amendment / evaluation_trial_withdraw.', null=True),
        ),
        migrations.AlterField(
            model_name='evaluationdataset',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the dataset was ORIGINALLY finalized. Immutable once set — never rewritten, even by a later post-finalization amendment (BPA-5.1), so the original finalization date always remains reconstructable.', null=True),
        ),
    ]
