# Generated by Django 4.2.21 on 2026-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0029_evaluationdataset_amended_after_finalization_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenesstransaction',
            name='evidence_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
