# Generated by Django 4.2.21 on 2026-09-04 18:09

from django.db import migrations, models


def dedupe_evidence_hashes(apps, schema_editor):
    """
    v2.1.16 Final Hardening Patch (Codex NO-GO #3): the AddConstraint
    operations below turn evidence_hash/evidence_pixel_hash into unique
    columns (scoped to non-blank values, via the same condition the
    constraints themselves use). Applying a UniqueConstraint to a table that
    already contains duplicate non-blank values fails the migration outright
    and leaves the schema mid-upgrade -- unacceptable on an installed
    deployment's database. Any pre-existing duplicates (e.g. rows written by
    an earlier build of this app, before the uniqueness invariant existed)
    are resolved here first, non-destructively: for each of the two hash
    columns, the OLDEST row (by created_at, then id) holding a given
    duplicate value keeps it; every later duplicate has ONLY that one
    colliding column blanked out -- every other field on the row (embedding,
    scores, beneficiary/event/operator linkage, audit trail) is left
    untouched, so no verification history is lost.

    Blanking is safe specifically because '' is excluded from both the
    uniqueness condition (Q(field__gt='')) and from every replay-hash lookup
    in verification/views.py (.exclude(evidence_hash='') / filtered by
    field=value, which a blank value never matches). A blanked row simply
    stops being replay-checked against by THAT hash type -- it is still
    covered by whichever of evidence_hash/evidence_pixel_hash/evidence_phash
    remains unblanked, and by definition it was the older of two colliding
    attempts on record, not a proof still in active use (LivenessTransaction
    tokens are single-use and short-lived; a duplicate hash surviving to
    this migration reflects historical data, not a live in-flight token).
    """
    LivenessTransaction = apps.get_model('verification', 'LivenessTransaction')

    for field in ('evidence_hash', 'evidence_pixel_hash'):
        seen_values = set()
        rows = (
            LivenessTransaction.objects
            .exclude(**{field: ''})
            .order_by('created_at', 'id')
            .values_list('id', field)
        )
        for row_id, value in rows:
            if value in seen_values:
                LivenessTransaction.objects.filter(id=row_id).update(**{field: ''})
            else:
                seen_values.add(value)


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0030_liveness_evidence_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenesstransaction',
            name='evidence_phash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='livenesstransaction',
            name='evidence_pixel_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='livenesstransaction',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        # v2.1.16 Final Hardening Patch (Codex NO-GO #3) -- must run AFTER
        # evidence_pixel_hash exists (it's part of the dedupe) and BEFORE the
        # unique constraints below (which is exactly what would fail if
        # duplicates survive).
        migrations.RunPython(dedupe_evidence_hashes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='livenesstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('evidence_hash__gt', '')), fields=('evidence_hash',), name='unique_nonblank_liveness_evidence_hash'),
        ),
        migrations.AddConstraint(
            model_name='livenesstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('evidence_pixel_hash__gt', '')), fields=('evidence_pixel_hash',), name='unique_nonblank_liveness_evidence_pixel_hash'),
        ),
    ]
