# Generated by Django 4.2.29 on 2026-03-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiary_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile photo for identification.', null=True, upload_to='beneficiaries/profile_pics/'),
        ),
    ]
