# Generated by Django 4.2.29 on 2026-03-22 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beneficiaries', '0004_beneficiary_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('valid_id_type', models.CharField(max_length=50)),
                ('valid_id_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='beneficiaries.beneficiary')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_representatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fans_representatives',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
