# Generated by Django 4.2.21 on 2026-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0008_sync_status_and_offline_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Human-readable reason for the last sync failure, conflict, or rejection. Cleared on successful sync.'),
        ),
    ]
