# Generated by Django 4.2.21 on 2026-05-24 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beneficiaries', '0010_add_house_no_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_match_beneficiary',
            field=models.ForeignKey(blank=True, help_text='Existing beneficiary whose face matched this registration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_registrations', to='beneficiaries.beneficiary'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_match_score',
            field=models.FloatField(blank=True, help_text='Face similarity score between this record and the matched beneficiary (0-1).', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_review_notes',
            field=models.TextField(blank=True, help_text='Admin notes recorded during duplicate review.'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_review_required',
            field=models.BooleanField(default=False, help_text='True when a face duplicate was detected at registration. Requires admin review.'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the duplicate review was completed.', null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='duplicate_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed and resolved the duplicate flag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reviews_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
