# Generated by Django 4.2.21 on 2026-08-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0013_shared_representative_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deceased', 'Deceased'), ('pending', 'Pending'), ('disapproved', 'Disapproved')], default='pending', max_length=12),
        ),
    ]
