# Generated by Django 4.2.21 on 2026-08-27 13:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_repair_legacy_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='assigned_office',
            field=models.CharField(blank=True, help_text='Where the user belongs/works (Assigned Office / Unit). Not the officer title.', max_length=200),
        ),
        migrations.AlterField(
            model_name='officerposition',
            name='is_unique',
            field=models.BooleanField(default=False, help_text='Only one active user can hold this position at a time. Board of Director is non-unique (multiple holders allowed).'),
        ),
    ]
