# Generated by Django 4.2.21 on 2026-08-28 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username_entered', models.CharField(help_text='Username as typed by the requester (may not match any account).', max_length=150)),
                ('contact_note', models.TextField(help_text='How to reach the requester, or why they believe they are locked out.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_password_reset_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Matched account, if username_entered corresponds to one. Null for unmatched/junk requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fans_password_reset_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
