# Generated by Django 4.2.21 on 2026-08-31 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_password_reset_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='make_password() digest of the 6-digit code — never the plaintext code.', max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Set once the correct code has been entered; required before the reset step.', null=True)),
                ('consumed_at', models.DateTimeField(blank=True, help_text='Set once this OTP has actually been used to change the password.', null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='Set when a newer OTP was issued for the same user, superseding this one.', null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fans_password_reset_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='fans_passwo_user_id_8fa3d1_idx')],
            },
        ),
    ]
