# Generated by Django 4.2.21 on 2026-08-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_phase6_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suffix',
            field=models.CharField(blank=True, help_text='e.g. Jr., Sr., II, III', max_length=20),
        ),
    ]
