# Generated by Django 4.2.21 on 2026-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_phase9_staff_name_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officerposition',
            options={'ordering': ['level', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='officerposition',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Hierarchy tier. Positions sharing the same level render side-by-side as equivalent-rank siblings (e.g. two Vice Presidents). Lower = higher in the chart.'),
        ),
        migrations.AlterField(
            model_name='officerposition',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sort order within (and across) levels — does not affect rank/tier by itself.'),
        ),
    ]
