# Generated by Django 4.2.21 on 2026-08-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_add_submit_frame_integrity_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('register', 'Registration'), ('verify', 'Verification'), ('override', 'Override'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_deactivate', 'User Deactivated'), ('config_change', 'Config Changed'), ('fallback', 'Fallback Triggered'), ('update', 'Record Updated'), ('face_update_request', 'Face Update Requested'), ('face_update_approved', 'Face Update Approved'), ('face_update_rejected', 'Face Update Rejected'), ('manual_verify_request', 'Manual Verification Requested'), ('manual_verify_approved', 'Manual Verification Approved'), ('manual_verify_rejected', 'Manual Verification Rejected'), ('claim', 'Claim Recorded'), ('special_claim_request', 'Special Claim Requested'), ('special_claim_approved', 'Special Claim Approved'), ('special_claim_rejected', 'Special Claim Rejected'), ('register_approved', 'Registration Approved'), ('register_rejected', 'Registration Rejected'), ('duplicate_face', 'Duplicate Face Detected'), ('sync_accepted', 'Sync Accepted'), ('sync_conflict', 'Sync Conflict'), ('sync_rejected', 'Sync Rejected'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset by Admin'), ('report_export', 'Report Exported'), ('claim_pending', 'Claim Queued (No Event)'), ('claim_pending_approved', 'Pending Claim Approved'), ('claim_pending_rejected', 'Pending Claim Rejected'), ('auto_approved', 'Auto-Approved by System'), ('record_approved', 'Record Manually Approved'), ('record_rejected', 'Record Rejected'), ('payout_cancelled', 'Payout Cancelled'), ('payout_failed', 'Payout Marked Failed'), ('payout_override', 'Payout Edited (Admin Override)'), ('payout_fallback_released', 'Fallback Payout Released'), ('duplicate_payout_attempt', 'Duplicate Payout Attempt Blocked'), ('verify_no_face', 'Verify Denied: No Face in Frame'), ('verify_multiple_faces', 'Verify Denied: Multiple Faces in Frame'), ('verify_subject_changed', 'Verify Denied: Subject Changed After Liveness'), ('verify_tx_stale', 'Verify Denied: Liveness Proof Stale/Reused'), ('verify_frame_invalid', 'Verify Denied: Final Frame Invalid'), ('shared_rep_flagged', 'Shared Representative Flagged for Review'), ('shared_rep_approved', 'Shared Representative Approved'), ('shared_rep_rejected', 'Shared Representative Rejected'), ('shared_rep_docs_required', 'Shared Representative: Document Requested'), ('shared_rep_blocked', 'Shared Representative Blocked (Suspicious)')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', 'timestamp'], name='fans_audit__user_id_45a36a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='fans_audit__action_ffb167_idx'),
        ),
    ]
