# Generated by Django 4.2.21 on 2026-08-28 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0010_add_backup_and_password_reset_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('approval_reminder', 'Approval Reminder'), ('fraud_alert', 'Fraud Alert'), ('verification_review', 'Verification Review'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, help_text='Resolved path to navigate to on click.', max_length=500)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fans_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='fans_notifi_recipie_1f1c52_idx')],
            },
        ),
    ]
