# Generated by Django 4.2.21 on 2026-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_add_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', help_text='Same LOW/MEDIUM/HIGH scale as fraud risk scoring, for visual consistency.', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('approval_required', 'Approval Required'), ('approval_reminder', 'Approval Reminder'), ('verification_review', 'Verification Review'), ('fraud_alert', 'Fraud Alert'), ('security_alert', 'Security Alert'), ('password_reset_request', 'Password Reset Request'), ('system_alert', 'System Alert')], db_index=True, default='system_alert', max_length=25),
        ),
    ]
